defaults:
  #  - override hydra/launcher: submitit_slurm
  - override hydra/launcher: submitit_local

seed: 0

# dataset should be one of {center3, cluster3, diagonal4, cluster10, cross10, diagonal28, diamond28, discrete_8gaussians}
dataset: discrete_8gaussians
#vardeq: True
#num_flows: 16
#num_dequant_flows: 4
#hdims: [256, 256]
flatten: False
binary_flows: True
bf:
  architecture: cnn
  num_flows: 8
  M: 128
  ks: 3
  pad: 1
  conditional: False
  conditional_classes: 8
linear_codes: False
bits: 8
#dequantization: voronoi

#embedding_dim: 2
#actfn: relu

#cond_embed_dim: 8

#block_transform: affine
#num_mixtures: 32

# base should be one of {gaussian, resampled, arbernoulli}
base: arbernoulli
arbernoulli:
  M: 128
  ks: 3
  pad: 1
  conditional: False
  conditional_classes: 8
#resampled:
#  actfn: relu
#  hdims: [256, 256]

iterations: 100000
#iterations: 10
batch_size: 200
#batch_size: 1
test_batch_size: 200
lr: 1e-3

num_test_samples: 10


hydra:
  run:
    dir: ./exp_local/discrete2d/${dataset}/${now:%Y.%m.%d}/${now:%H%M%S}
  sweep:
    dir: ./exp/discrete2d/${dataset}/${now:%Y.%m.%d}/${now:%H%M%S}
    subdir: ${hydra.job.num}
  launcher:
    #    max_num_timeout: 100000
    #    timeout_min: 1440
    #    partition: learnfair
    mem_gb: 64
    gpus_per_node: 1